name: ui
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.17.1 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook: 2.0.5-beta
  flutter_svg: ^1.0.3
  auto_size_text: 3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/ui/assets/images/map.png
    - packages/ui/assets/images/pill.svg
    - packages/ui/assets/images/oval3.svg
    - packages/ui/assets/images/arrowleft.svg
    - packages/ui/assets/images/homeindicator.svg
    - packages/ui/assets/images/xsmall.svg
    - packages/ui/assets/images/circle.svg
    - packages/ui/assets/images/location.svg
    - packages/ui/assets/images/buttonbg.svg
    - packages/ui/assets/images/shoppingcart.svg
    - packages/ui/assets/images/bg.svg
    - packages/ui/assets/images/chevrondownblack.svg
    - packages/ui/assets/images/oval2.svg
    - packages/ui/assets/images/sortlightgray.svg
    - packages/ui/assets/images/clockwhite.svg
    - packages/ui/assets/images/planelightgray.svg
    - packages/ui/assets/images/menu.svg
    - packages/ui/assets/images/xlightgray.svg
